[theme]
primaryColor = "#FF0000"
backgroundColor = "#0F0F0F"
secondaryBackgroundColor = "#1F1F1F"
textColor = "#FFFFFF"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
